#!/bin/bash
set -e

if [ "$1" == "help" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
  echo "$1 [push]"
  exit 0
fi

CURRENTDIR=`dirname "$(readlink -f "$0")"`

echo "Running unit tests"
cd $CURRENTDIR/python
python3 -m unittest discover

cd $CURRENTDIR/docker/core
./build $1
