FROM t0rx/rpi-python3

RUN pip3 install paho-mqtt
# Note that pyyaml is already installed in the base image

RUN mkdir -p /opt/dancecard /etc/dancecard
VOLUME /etc/dancecard

WORKDIR /opt/dancecard
COPY python/*.py python/

ENTRYPOINT [ "python3", "python/dancecard.py" ]
